#!/usr/bin/env python

import os
import re
import argh
from datetime import date

import unicodedata


def slugify(value):
    """
    Stolen (and adapted) from django master tree.
    """
    value = unicodedata.normalize('NFKD', value).encode('ascii', 'ignore').decode('ascii')
    value = re.sub('[^\w\s-]', '', value).strip().lower()
    return re.sub('[-\s]+', '-', value)


def current_year():
    return date.today().year


def install_blog():
    if not os.path.exists(os.path.expanduser("~/code/blog/")):
        os.makedirs(os.path.expanduser("~/code/blog/"))

    if not os.path.exists(os.path.expanduser("~/code/blog/worlddomination.be/")):
        os.system("cd ~/code/blog/ && git clone https://github.com/psycojoker/worlddomination.be && cd worlddomination.be && make")


def post(title):
    install_blog()
    os.system("vi %s" % os.path.expanduser("~/code/blog/worlddomination.be/content/blog/%s/%s.html" % (current_year(), slugify(title.decode("Utf-8")))))


parser = argh.ArghParser()
parser.add_commands([post])

if __name__ == '__main__':
    parser.dispatch()
